version: "3"

services:
  api:
    image: aisapi
    build: ./api
    ports:
      - 8080:8080
    depends_on:
      - "postgres"

  postgres:
    image: postgres
    container_name: 'postgres'
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
volumes:
  pgdata: